# Training Hyperparameters
epochs: 200
fno_epochs: 100
ebm_epochs: 100
patience: 15
accumulation_steps: 4

# Optimizer and Scheduler
fno_learning_rate: 0.001
ebm_learning_rate: 0.0001
fno_optimizer_config:
  type: adam
  lr: 1e-4
  weight_decay: 0.01

ebm_optimizer_config:
  type: adamw
  lr: 5e-5
  betas: [0.9, 0.999]

fno_scheduler_config:
  type: cosine_annealing_warm_restarts_with_decay
  T_0: 10
  T_mult: 1.0
  freq_mult: 0.9
  eta_min: 0
  decay: 0.9

ebm_scheduler_config:
  type: step_lr
  step_size: 30
  gamma: 0.1

# Model Parameters
fno_modes: 16
fno_width: 64
ebm_hidden_dim: 128

# Physics and MCMC
pde_type: 'poisson' # Can be 'poisson', 'heat', etc.
lambda_phys: 1.0
mcmc_steps: 60
mcmc_step_size: 0.005

# Data and Paths
data_path: './data/poisson.mat'
checkpoint_dir: './checkpoints'
batch_size: 16
grid_size: 64
n_train: 1000
n_test: 200