# Training Hyperparameters
epochs: 200
fno_epochs: 100
ebm_epochs: 100
patience: 15
accumulation_steps: 4

# Optimizer and Scheduler
fno_learning_rate: 0.001
ebm_learning_rate: 0.0001
fno_optimizer_config:
  type: adam
  lr: 1e-4
  weight_decay: 0.01

ebm_optimizer_config:
  type: adamw
  lr: 5e-5
  betas: [0.9, 0.999]

fno_scheduler_config:
  type: cosine_annealing_warm_restarts_with_decay
  T_0: 10
  T_mult: 1.0
  freq_mult: 0.9
  eta_min: 0
  decay: 0.9

ebm_scheduler_config:
  type: step_lr
  step_size: 30
  gamma: 0.1

# Model Parameters
fno_modes: 16
fno_width: 64
ebm_hidden_dim: 128

# Physics and MCMC
pde_type: 'poisson' # Can be 'poisson', 'heat', etc.
lambda_phys: 1.0
mcmc_steps: 60
mcmc_step_size: 0.005

# Data and Paths
data_path: './data/poisson.mat'
data_dir: './data'
checkpoint_dir: './checkpoints'
batch_size: 16
grid_size: 64
n_train: 1000
n_test: 200
num_workers: 4
save_data: true  # Save generated datasets to disk

# Dataset Generation Parameters
data_seed: 42  # Random seed for reproducible data generation
train_test_split: 0.8  # Training / (Training + Validation) ratio

# PDE Selection
# Options: 'darcy', 'burgers', 'poisson'
pde_type: 'darcy'

# Complexity Level
# Options: 'simple', 'medium', 'hard'
# Controls roughness of input fields (GP length scale for source/permeability)
complexity: 'medium'

# Noise Configuration
# Noise type: 'gaussian', 'heteroscedastic', 'spatially_correlated', 'mixed', or null (no noise)
noise_type: 'heteroscedastic'

# Gaussian noise parameters (if noise_type='gaussian')
noise_level: 0.01  # Standard deviation of white noise

# Heteroscedastic noise parameters (if noise_type='heteroscedastic')
base_noise: 0.001  # Minimum noise floor
scale_factor: 0.02  # Noise proportional to signal (2% relative noise)

# Spatially correlated noise parameters (if noise_type='spatially_correlated')
spatial_noise_level: 0.01
correlation_length: 3.0  # In grid points

# Mixed noise parameters (if noise_type='mixed')
gaussian_level: 0.005
hetero_scale: 0.01
spatial_level: 0.003
mixed_correlation_length: 2.0

# Burgers-specific parameters (only used if pde_type='burgers')
burgers_nx: 256  # Spatial resolution
burgers_nt: 100  # Temporal resolution (output timesteps)
burgers_viscosity: 0.01  # Viscosity coefficient
burgers_T: 1.0  # Final time
burgers_L: 6.283185307179586  # Domain length (2Ï€)